
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjfnyzrjqvrvqmyitwnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZm55enJqcXZydnFteWl0d25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjgxOTcsImV4cCI6MjA1ODM0NDE5N30.0hmxw7z371ItaGtouPL8s21vudYhL48JBVX0giyDJVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
